services:

  redis:
    image: bitnami/redis:latest
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"

  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"

  db:
    image: postgres:13
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  db_create:
    build:
      context: .
    command: bash -c 'bin/rails db:create && bin/rails db:migrate && bin/rails db:seed'
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/clutterchat

  web:
    build:
      context: .
    command: foreman start -f Procfile.dev
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    depends_on:
      - db
      - db_create
    volumes:
      - .:/clutterchat

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command: http http://web:3000 --log stdout --hostname relaxing-midge-warm.ngrok-free.app
    links:
      - web
    depends_on:
      - web
    env_file:
      - ./.env
    ports:
      - 4040:4040
