default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "test") %>
  host: db
  port: 5432

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test
